config/routes.rb
Rails.application.routes.draw do
  resources :pagos
  resources :pro_fars
  resources :disponibilidads
  resources :lab_fars
  resources :sessions
  resources :productos
  resources :nombres
  resources :presentacions
  resources :sustancia
  resources :tipo_plans
  resources :plan_pacientes
  resources :laboratorios
  resources :farmacia
  
   get 'logout' => 'sessions#logout'
   get 'login' => 'sessions#new'
   get 'change_password' => 'sessions#new_password'
    get 'reset_password' => 'sessions#reset_password'
   post '/reset_password_update', to: 'sessions#reset_password_update'
   post '/change_password_update', to: 'sessions#update_contrasena'
   get 'lab_farmacia' => 'lab_fars#lab_farm'

   get '/pro_farmacia/:id', to: 'pro_fars#pro_farm'
   
   get '/pro_farmacia_edit/:id', to: 'pro_fars#pro_farm_edit'
   put '/pro_farmacia_update/:id', to: 'pro_fars#pro_farm_update'
   put '/farmacia_verificado/:id', to: 'farmacia#update_verificado'
   get '/farmacias_verificadas', to: 'farmacia#farmacias_verificadas'  
  get '/producto/busqueda/:nombre', to: 'productos#busqueda'
  get '/laboratorio/busqueda/:nombre', to: 'laboratorios#busqueda'
  get '/plan_pacientes/busqueda/:nombre', to: 'plan_pacientes#busqueda'
  get '/presentaciones/busqueda/:nombre', to: 'presentacions#busqueda'
  get '/sustancias/busqueda/:nombre', to: 'sustancia#busqueda'
  get '/farmacias_verificadas/busqueda/:nombre', to: 'farmacia#busquedaVerificadas'
  get '/farmacia/busqueda/:nombre', to: 'farmacia#busqueda'
  get '/lab_fars/busqueda/:laboratorio_id', to: 'lab_fars#busqueda'
  get '/lab_fars/busquedalaboratoriosfarmacia/:laboratorio_id', to: 'lab_fars#busquedaLaboratoriosAgregados'
  get '/pro_fars/busquedaProductos/:laboratorio/:producto_id', to: 'pro_fars#showBusqueda'
  get '/pro_fars/pro_farmBusqueda/:laboratorio/:producto_id', to: 'pro_fars#pro_farmBusqueda'
  get '/pagos/busqueda/:nombre', to: 'pagos#busqueda'

  

   put '/laboratorio_activo/:id', to: 'laboratorios#activo_update'
   put '/planpaciente_activo/:id', to: 'plan_pacientes#activo_update'
   put '/presentacion_activo/:id', to: 'presentacions#activo_update'
   put '/sustancia_activo/:id', to: 'sustancia#activo_update'
   put '/producto_activo/:id', to: 'productos#activo_update'
   put '/pagos/:id/:idfarmacia', to: 'pagos#update'

   get '/farmacia_plan_paciente/:id', to: 'plan_pacientes#farmacia_plan_paciente'
   get '/plan_paciente/:id', to: 'productos#Plan_Paciente'

     

   root 'sessions#logout'

   namespace :api do
    namespace :v1 do
      get '/laboratorio_consulta', to: 'consultas#index'
      get '/farmacias_cercanas', to: 'consultas#FarmaciasCercanas'
      get '/infoFarmacia/:id', to: 'consultas#InfoFarmacia'
      get '/searchProducto/:nombre', to: 'consultas#SearchProducto'
      get '/infoProducto/:id', to: 'consultas#InfoProducto'
      get '/infoPlanPaciente/:id', to: 'consultas#InfoPlanPaciente'
      get '/FarmaciasCercanaSearch/:id', to: 'consultas#FarmaciasCercanaSearch'
      get '/FarmaciaProductoSearch/:id', to: 'consultas#infoFarmaciaProducto'
    end
  end

  

  

end

app/models/pago.rb
class Pago < ActiveRecord::Base
  belongs_to :farmacia
  	validates :numcomprobante,  presence:  { message: "Campo obligatorio" }
    validates :numcomprobante,  numericality: {  message: "Ingrese un número.",only_integer: true }
end

app/controllers/pagos_controller.rb
class PagosController < ApplicationController
  before_action :set_pago, only: [:show, :edit, :update, :destroy]
  before_action :autenticacion
  before_action :verificarUsuario, only: [:update, :destroy, :index]
    require 'sendgrid-ruby'
  include SendGrid
  

  # GET /pagos
  # GET /pagos.json
  def index

    sql = "select pagos.id, pagos.numcomprobante, pagos.verificado,pagos.farmacium_id, farmacia.nombre from pagos, farmacia where pagos.farmacium_id = farmacia.id"
    @pagos =  Pago.paginate_by_sql(sql, :page => params[:page], :per_page => 9)
  end
  def busqueda
    nombre = params[:nombre]
      
   sql = "select pagos.id, pagos.numcomprobante, pagos.verificado,pagos.farmacium_id, farmacia.nombre from  pagos, farmacia where pagos.farmacium_id = farmacia.id and LOWER(farmacia.nombre) like LOWER('%#{nombre}%')"
    @pagos =  Pago.paginate_by_sql(sql, :page => params[:page], :per_page => 9)
    render :template => "pagos/index"
  end


  # GET /pagos/1
  # GET /pagos/1.json
  def show
  end

  # GET /pagos/new
  def new
    @pago = Pago.new
  end

  # GET /pagos/1/edit
  def edit
  end

  # POST /pagos
  # POST /pagos.json
  def create

    @pago = Pago.new(pago_params)

    @pago.farmacium_id = session[:farmacia_id]
    @pago.numcomprobante = params[:pago][:numcomprobante]


    respond_to do |format|
      if (params[:pago][:numcomprobante].length >=  11)
      format.html { redirect_to "/lab_fars", notice: 'Comprobante no puede tener mas de 11 carácteres.' }
      else
      if @pago.save
         format.html { redirect_to "/lab_fars", notice: 'Comprobante se envió satisfactoriamente.' }
      else
        format.html { redirect_to "/lab_fars", notice: 'Reporte de pago no debe estar en blanco.' }
        
        end
      end
    end
  end

  # PATCH/PUT /pagos/1
  # PATCH/PUT /pagos/1.json
  def update
     respond_to do |format|
       idfarmacia = params[:idfarmacia]
        id = params[:id]
        
        Pago.where(id: id).update_all(verificado: true )
        farmacia =  Farmacium.find_by_sql("select nombre, correo, cant_lab from farmacia where id = #{idfarmacia} ").first
        
         cant = farmacia.cant_lab + 1 
         Farmacium.where(id:idfarmacia).update_all(cant_lab: cant )
         # notificar a la farmacia por correo
    from = Email.new(email: 'diegogarciafonseca@gmail.com')
    to = Email.new(email: "#{farmacia.correo}")
    subject = 'Verificación de pago laboratorios'
    content = Content.new(type: 'text/plain', value: "Estimada Farmacia: #{farmacia.nombre}, su compobante número #{id}, sea verificado con éxito.")
    mail = Mail.new(from, subject, to, content)

    sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'])
    response = sg.client.mail._('send').post(request_body: mail.to_json)
    puts response.status_code
    puts response.body
    puts response.headers

       msg = { :status => "ok", :message => "Actualizado!" }
        format.json { render :json => msg }
    end
  end

  # DELETE /pagos/1
  # DELETE /pagos/1.json
  def destroy
    @pago.destroy
    respond_to do |format|
      format.html { redirect_to pagos_url, notice: 'Pago was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pago
      @pago = Pago.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pago_params
      params.require(:pago).permit(:farmacia_id, :numcomprobante, :verificado)
    end
end

app/helpers/pagos_helper.rb
module PagosHelper
end

app/views/pagos/_form.html.erb
<%= bootstrap_form_for(@pago) do |f| %>

<div class="col-md-4 col-lg-4 col-md-offset-4 col-lg-offset-4  col-xs-6 col-sm-6">

 <div class="field">
    <%= f.number_field :numcomprobante , label: "Número de comprobante" %>
  </div>
  <div class="field">
    <%= f.text_field :monto , label: "Monto Colones" %>
  </div>
 
  <div class="field">
    <%= f.number_field :cantLab , label: "Cantidad Laboratorios"%>
  </div>
  
  <div class="actions">
 <%= f.submit class: 'btn btn-success ' %>
  </div>
  
<% end %>
</div>

app/views/pagos/edit.html.erb
<h1>Editing Pago</h1>

<%= render 'form' %>

<%= link_to 'Show', @pago %> |
<%= link_to 'Back', pagos_path %>

app/views/pagos/index.html.erb
<script type="text/javascript">
var msj = "<%= notice %>";
  $(document).ready(function() {
  if(msj!='')
    swal(msj, "", "success")

});
</script>
<h1 class="text-center"> <span class="label label-default">Lista pagos de Farmacia</span></h1>
<br>

  <div class="col-lg-3 col-md-3 col-xs-4 col-sm-4 col-md-offset-2 col-lg-offset-2">
   <input type="text" class="form-control"  placeholder="Nombre" name="nombre" id="nombre">
  </div>
 <div class="col-lg-2 col-md-2 col-xs-3 col-sm-3">
  <button type="submit" class="btn btn-success" onclick="busquedaPagos();"><span class="glyphicon glyphicon-search" aria-hidden="true"></span> Buscar</button>
  </div>
<div class="col-lg-7 col-md-7 col-md-offset-2 col-lg-offset-2  col-xs-12 col-sm-12">
<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th>Farmacia</th>
      <th>Número comprobante</th>
      <th>Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @pagos.each do |pago| %>
      <tr>
        <td width="20%"><%= pago.nombre %></td>
        <td width="20%"><%= pago.numcomprobante %></td>
        <td width="15%"> <% if pago.verificado == true %> 

            <label>Verificado</label>
         <% else %> 

             <label><input type="checkbox" value="" onclick="verificarPago(<%= pago.id %>, <%= pago.farmacium_id %>);">  Verificar</label>
        <% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>
 <div class="col-lg-8 col-md-8 col-md-offset-4 col-lg-offset-4 col-xs-offset-4 col-sm-offset-4 col-xs-8 col-sm-8" >
        <%= will_paginate @pagos, renderer: BootstrapPagination::Rails %>
    </div>

app/views/pagos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Farmacia:</strong>
  <%= @pago.farmacia %>
</p>

<p>
  <strong>Monto:</strong>
  <%= @pago.monto %>
</p>

<p>
  <strong>Numcomprobante:</strong>
  <%= @pago.numcomprobante %>
</p>

<p>
  <strong>Cantlab:</strong>
  <%= @pago.cantLab %>
</p>

<%= link_to 'Edit', edit_pago_path(@pago) %> |
<%= link_to 'Back', pagos_path %>