config/routes.rb
Rails.application.routes.draw do
  resources :pagos
  resources :pro_fars
  resources :disponibilidads
  resources :lab_fars
  resources :sessions
  resources :productos
  resources :nombres
  resources :presentacions
  resources :sustancia
  resources :tipo_plans
  resources :plan_pacientes
  resources :laboratorios
  resources :farmacia
  
   get 'logout' => 'sessions#logout'
   get 'login' => 'sessions#new'
   get 'change_password' => 'sessions#new_password'
    get 'reset_password' => 'sessions#reset_password'
   post '/reset_password_update', to: 'sessions#reset_password_update'
   post '/change_password_update', to: 'sessions#update_contrasena'
   get 'lab_farmacia' => 'lab_fars#lab_farm'

   get '/pro_farmacia/:id', to: 'pro_fars#pro_farm'
   
   get '/pro_farmacia_edit/:id', to: 'pro_fars#pro_farm_edit'
   put '/pro_farmacia_update/:id', to: 'pro_fars#pro_farm_update'
   put '/farmacia_verificado/:id', to: 'farmacia#update_verificado'
   get '/farmacias_verificadas', to: 'farmacia#farmacias_verificadas'  
  get '/producto/busqueda/:nombre', to: 'productos#busqueda'
  get '/laboratorio/busqueda/:nombre', to: 'laboratorios#busqueda'
  get '/plan_pacientes/busqueda/:nombre', to: 'plan_pacientes#busqueda'
  get '/presentaciones/busqueda/:nombre', to: 'presentacions#busqueda'
  get '/sustancias/busqueda/:nombre', to: 'sustancia#busqueda'
  get '/farmacias_verificadas/busqueda/:nombre', to: 'farmacia#busquedaVerificadas'
  get '/farmacia/busqueda/:nombre', to: 'farmacia#busqueda'
  get '/lab_fars/busqueda/:laboratorio_id', to: 'lab_fars#busqueda'
  get '/lab_fars/busquedalaboratoriosfarmacia/:laboratorio_id', to: 'lab_fars#busquedaLaboratoriosAgregados'
  get '/pro_fars/busquedaProductos/:laboratorio/:producto_id', to: 'pro_fars#showBusqueda'
  get '/pro_fars/pro_farmBusqueda/:laboratorio/:producto_id', to: 'pro_fars#pro_farmBusqueda'
  get '/pagos/busqueda/:nombre', to: 'pagos#busqueda'

  

   put '/laboratorio_activo/:id', to: 'laboratorios#activo_update'
   put '/planpaciente_activo/:id', to: 'plan_pacientes#activo_update'
   put '/presentacion_activo/:id', to: 'presentacions#activo_update'
   put '/sustancia_activo/:id', to: 'sustancia#activo_update'
   put '/producto_activo/:id', to: 'productos#activo_update'
   put '/pagos/:id/:idfarmacia', to: 'pagos#update'

   get '/farmacia_plan_paciente/:id', to: 'plan_pacientes#farmacia_plan_paciente'
   get '/plan_paciente/:id', to: 'productos#Plan_Paciente'

     

   root 'sessions#logout'

   namespace :api do
    namespace :v1 do
      get '/laboratorio_consulta', to: 'consultas#index'
      get '/farmacias_cercanas', to: 'consultas#FarmaciasCercanas'
      get '/infoFarmacia/:id', to: 'consultas#InfoFarmacia'
      get '/searchProducto/:nombre', to: 'consultas#SearchProducto'
      get '/infoProducto/:id', to: 'consultas#InfoProducto'
      get '/infoPlanPaciente/:id', to: 'consultas#InfoPlanPaciente'
      get '/FarmaciasCercanaSearch/:id', to: 'consultas#FarmaciasCercanaSearch'
      get '/FarmaciaProductoSearch/:id', to: 'consultas#infoFarmaciaProducto'
    end
  end

  

  

end

app/models/plan_paciente.rb
class PlanPaciente < ActiveRecord::Base
  validates :nombre,  presence:  { message: "Campo obligatorio" }
  belongs_to :laboratorio
end

app/controllers/plan_pacientes_controller.rb
class PlanPacientesController < ApplicationController
  before_action :set_plan_paciente, only: [:show, :edit, :update, :destroy]
   before_action :autenticacion
   before_action :verificarUsuario, except: [:farmacia_plan_paciente]
  # GET /laboratorios
  # GET /plan_pacientes
  # GET /plan_pacientes.json
  def index
    sql = "select * from plan_pacientes order by nombre"
    @plan_pacientes=  PlanPaciente.paginate_by_sql(sql, :page => params[:page], :per_page => 7)

  end
   def busqueda
    nombre = params[:nombre]      
   sql = "select * from plan_pacientes where LOWER(nombre) like LOWER('%#{nombre}%') order by nombre"
    @plan_pacientes=  PlanPaciente.paginate_by_sql(sql, :page => params[:page], :per_page => 7)
    render :template => "plan_pacientes/index"
  end

  # GET /plan_pacientes/1
  # GET /plan_pacientes/1.json
  def show
       @tipo_plan = TipoPlan.new
       @plan_Paciente_Paciente = TipoPlan.where(["plan_paciente_id = ? and tipo = ?", params[:id], "Paciente"])
       @plan_Paciente_Farmacia = TipoPlan.where(["plan_paciente_id = ? and tipo = ?", params[:id], "Farmacia"])
  end
   # GET /plan_pacientes_farmacia/1
  # Metodo para que la farmacia vea la lista de los requisitos del plan
  def farmacia_plan_paciente
     @plan_Paciente =  PlanPaciente.find(params[:id])
      @plan_Paciente_Farmacia = TipoPlan.where(["plan_paciente_id = ? and tipo = ?", params[:id], "Farmacia"])
      render :template => "plan_pacientes/farmacia_planpaciente"
  end

  # GET /plan_pacientes/new
  def new    
    @laboratorios =  Laboratorio.find_by_sql("Select id, nombre from laboratorios where  not exists (select * from plan_pacientes where plan_pacientes.laboratorio_id = laboratorios.id )")    
    @plan_paciente = PlanPaciente.new
  end

  # GET /plan_pacientes/1/edit
  def edit
    id =  PlanPaciente.where(["id = ? ", params[:id]]).first
    id = id.laboratorio_id
    @laboratorios =  Laboratorio.find_by_sql("Select id, nombre from laboratorios where not exists (select * from plan_pacientes where plan_pacientes.laboratorio_id = laboratorios.id and laboratorios.id <> #{id} )  ")
  end

  # POST /plan_pacientes
  # POST /plan_pacientes.json
  def create
    @plan_paciente = PlanPaciente.new(plan_paciente_params)

    respond_to do |format|
      if @plan_paciente.save
        format.html { redirect_to "/plan_pacientes/new", notice: 'Plan Paciente creado con éxito.' }
      else
        format.html { render :new }
        format.json { render json: @plan_paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plan_pacientes/1
  # PATCH/PUT /plan_pacientes/1.json
  def update
    respond_to do |format|
      if @plan_paciente.update(plan_paciente_params)
        format.html { redirect_to "/plan_pacientes", notice: 'Plan Paciente actualizado con éxito.' }
        
      else
        format.html { render :edit }
        format.json { render json: @plan_paciente.errors, status: :unprocessable_entity }
      end
    end
  end
  # Metodo para actualizar activo de Plan Paciente
  def activo_update
      respond_to do |format|
       activo = params[:plan_paciente][:activo]
        id = params[:id]
        PlanPaciente.where(id: id).update_all(activo: activo )
       msg = { :status => "ok", :message => "Actualizado!" }
        format.json { render :json => msg }
    end
  end

  # DELETE /plan_pacientes/1
  # DELETE /plan_pacientes/1.json
  def destroy
    @plan_paciente.destroy
    respond_to do |format|
      msg = { :status => "ok", :message => "Eliminado!" }
        format.json { render :json => msg }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan_paciente
      @plan_paciente = PlanPaciente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plan_paciente_params
      params.require(:plan_paciente).permit(:nombre, :laboratorio_id)
    end
end

app/helpers/plan_pacientes_helper.rb
module PlanPacientesHelper
end

app/views/plan_pacientes/_form.html.erb
<%= bootstrap_form_for(@plan_paciente) do |f| %>
 <div class="col-md-6 col-lg-6 col-md-offset-3 col-lg-offset-3  col-xs-12 col-sm-10">
  <div class="field">
    
    <%= f.text_field :nombre %>
  </div>
  
    <div class="field">
    <br>
    <%= f.collection_select :laboratorio_id, Laboratorio.find_by_sql("Select id, nombre from laboratorios where  not exists (select * from plan_pacientes where plan_pacientes.laboratorio_id = laboratorios.id ) order by nombre"), :id, :nombre , label: "Laboratorios"%>
    
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>
</div>

app/views/plan_pacientes/_linkprincipal.html.erb
<div class="col-lg-12 col-md-12  col-xs-12 col-sm-12">

     <a href="/plan_pacientes" class="btn btn-info">
         <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>	Plan Pacientes
          </a>
          
 </div>

app/views/plan_pacientes/edit.html.erb
<%= render 'linkprincipal' %>

<h1 class="text-center"> <span class="label label-default">Actualizar Plan Paciente</span></h1>
<%= render 'form' %>

app/views/plan_pacientes/farmacia_planpaciente.html.erb
<h1 class="text-center"></h1>
<h1 class="text-center"> <span class="label label-default">Pasos para registrar la farmacia al plan paciente: <%= @plan_Paciente.nombre %></span></h1>
<div class="col-lg-5 col-md-5 col-xs-6 col-sm-6 col-md-offset-3 col-lg-offset-3">
<table class="table table-striped table-condensed"">
  <thead>
    <tr>
      <th>Pasos a seguir:</th>
      
    </tr>
  </thead>

  <tbody>
    <% @plan_Paciente_Farmacia.each do |plan| %>
      <tr id="<%= plan.id %>">
        <td width="80%"><%= plan.descripcion   %></td>       
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/plan_pacientes/index.html.erb
<script type="text/javascript">
var msj = "<%= notice %>";
  $(document).ready(function() {
     
  if(msj!='')
    swal(msj, "", "success")

});
</script>
<h1 class="text-center"> <span class="label label-default">Plan Pacientes</span></h1>
<br>
  <div class="col-lg-3 col-md-3 col-xs-4 col-sm-4 col-md-offset-2 col-lg-offset-2">
   <input type="text" class="form-control"  placeholder="Nombre" name="nombre" id="nombre">
  </div>
 <div class="col-lg-2 col-md-2 col-xs-3 col-sm-3">
  <button type="submit" class="btn btn-success" onclick="busquedaPlanPaciente();"><span class="glyphicon glyphicon-search" aria-hidden="true"></span> Buscar</button>
  </div>

<div class="col-lg-8 col-md-8 col-md-offset-2 col-lg-offset-2  col-xs-12 col-sm-12">
<table class="table table-striped table-condensed"">
  <thead>
    <tr>
      <th>Nombre Plan Paciente</th>
      <th>Laboratorio</th>
      <th>Activo</th>
      <th>Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @plan_pacientes.each do |plan| %>
      <tr id="<%= plan.id %>">
        <td width="25 %"><%= plan.nombre %></td>
        <td width="25%"><%= plan.laboratorio.nombre %></td>
          <td width="15%"> <% if plan.activo == true %> 

            <label><input type="checkbox" value="" onclick="Activo(<%= plan.id %>, <%= plan.activo %>, 'planpaciente');" checked>Activo</label>
         <% else %> 

             <label><input type="checkbox" value="" onclick="Activo(<%= plan.id %>, <%= plan.activo %>,'planpaciente');">Activo</label>
        <% end %></td>
        <td width="20%">
          <a href="/plan_pacientes/<%= plan.id %>" class="btn btn-info">
         <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
          </a>
          <a href="/plan_pacientes/<%= plan.id %>/edit" class="btn btn-success">
            <span class="glyphicon glyphicon-edit" aria-hidden="true"></span> 
          </a>
           <button class="btn btn-danger" onclick="deletePlanPaciente(<%= plan.id %>)"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span> </button>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

</div>
<div class="col-md-6 col-lg-6 col-xs-10 col-sm-10 col-md-offset-2 col-lg-offset-2 ">
<%= link_to 'Nuevo plan paciente', new_plan_paciente_path, :class => "btn btn-success"%>
</div>
 <div class="col-lg-8 col-md-8 col-md-offset-4 col-lg-offset-4 col-xs-offset-4 col-sm-offset-4 col-xs-8 col-sm-8 " >
        <%= will_paginate @plan_pacientes, renderer: BootstrapPagination::Rails %>
    </div>

app/views/plan_pacientes/new.html.erb
<script type="text/javascript">
var msj = "<%= notice %>";
	$(document).ready(function() {
  if(msj!='')
  	swal(msj, "", "success")

});
</script>
<%= render 'linkprincipal' %>
<h1 class="text-center"> <span class="label label-default">Nuevo Plan Paciente</span></h1>

<%= render 'form' %>

app/views/plan_pacientes/show.html.erb
<script type="text/javascript">
var msj = "<%= notice %>";
  $(document).ready(function() {
  if(msj!='')
    swal(msj, "", "success")

});
</script>
<%= render 'linkprincipal' %>
 <br>
 <br>
<form class="form-group">
<div class="col-lg-5 col-md-5 col-xs-5 col-sm-5">
  <div class="form-group">
    <label for="exampleInputName2">Nombre Plan Paciente</label>
    <input type="text" class="form-control" id="exampleInputName2" value=" <%=@plan_paciente.nombre%>" readonly>
  </div>
</div>
<div class="col-lg-5 col-md-5 col-xs-5 col-sm-5">
  <div class="form-group">
    <label for="exampleInputEmail2">Laboratorio</label>
    <input type="text" class="form-control" id="exampleInputEmail2" value="<%=@plan_paciente.laboratorio.nombre %>" readonly>
  </div>
  </div>
 
  
</form>




<div class="col-lg-6 col-md-6 col-xs-12 col-sm-12">
  <h2 class="text-center"> <span class="label label-default">Pasos para el paciente:</span></h2>
    
  <%= bootstrap_form_for(@tipo_plan) do |f| %>
   <div class="field">
    <%= f.hidden_field :tipo, :value => 'Paciente' %>
  </div>
  <div class="field">
    <%= f.text_field :descripcion , label: "Descripción"%>
  </div>
  <div class="field">
  <%= f.hidden_field :plan_paciente_id, :value => @plan_paciente.id %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-success'%>
  </div>
<% end %>

<table class="table table-striped table-condensed"">
  <thead>
    <tr>
      <th>Descripción</th>
      <th>Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @plan_Paciente_Paciente.each do |plan| %>
      <tr id="<%= plan.id %>">
        <td width="80%"><%= plan.descripcion   %></td>
        <td width="8%">
           <button class="btn btn-danger" onclick="delete_tipoplan(<%= plan.id %>)"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Eliminar</button>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<div class="col-lg-6 col-md-6 col-xs-12 col-sm-12">
  <h2 class="text-center"> <span class="label label-default">Pasos para la Farmacia:</span></h2>
  <%= bootstrap_form_for(@tipo_plan) do |f| %>
   <div class="field">
    <%= f.hidden_field :tipo, :value => 'Farmacia' %>
  </div>
  <div class="field">
    <%= f.text_field :descripcion , label: "Descripción"%>
  </div>
  <div class="field">
  <%= f.hidden_field :plan_paciente_id, :value => @plan_paciente.id %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-success'%>
  </div>
<% end %>
<table class="table table-striped table-condensed"">
  <thead>
    <tr>
      <th>Descripción</th>
      <th>Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @plan_Paciente_Farmacia.each do |plan| %>
      <tr id="<%= plan.id %>">
        <td width="80%"><%= plan.descripcion   %></td>
        <td width="8%">
           <button class="btn btn-danger" onclick="delete_tipoplan(<%= plan.id %>)"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Eliminar</button>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>