config/routes.rb
Rails.application.routes.draw do
  resources :pagos
  resources :pro_fars
  resources :disponibilidads
  resources :lab_fars
  resources :sessions
  resources :productos
  resources :nombres
  resources :presentacions
  resources :sustancia
  resources :tipo_plans
  resources :plan_pacientes
  resources :laboratorios
  resources :farmacia
  
   get 'logout' => 'sessions#logout'
   get 'login' => 'sessions#new'
   get 'change_password' => 'sessions#new_password'
    get 'reset_password' => 'sessions#reset_password'
   post '/reset_password_update', to: 'sessions#reset_password_update'
   post '/change_password_update', to: 'sessions#update_contrasena'
   get 'lab_farmacia' => 'lab_fars#lab_farm'

   get '/pro_farmacia/:id', to: 'pro_fars#pro_farm'
   
   get '/pro_farmacia_edit/:id', to: 'pro_fars#pro_farm_edit'
   put '/pro_farmacia_update/:id', to: 'pro_fars#pro_farm_update'
   put '/farmacia_verificado/:id', to: 'farmacia#update_verificado'
   get '/farmacias_verificadas', to: 'farmacia#farmacias_verificadas'  
  get '/producto/busqueda/:nombre', to: 'productos#busqueda'
  get '/laboratorio/busqueda/:nombre', to: 'laboratorios#busqueda'
  get '/plan_pacientes/busqueda/:nombre', to: 'plan_pacientes#busqueda'
  get '/presentaciones/busqueda/:nombre', to: 'presentacions#busqueda'
  get '/sustancias/busqueda/:nombre', to: 'sustancia#busqueda'
  get '/farmacias_verificadas/busqueda/:nombre', to: 'farmacia#busquedaVerificadas'
  get '/farmacia/busqueda/:nombre', to: 'farmacia#busqueda'
  get '/lab_fars/busqueda/:laboratorio_id', to: 'lab_fars#busqueda'
  get '/lab_fars/busquedalaboratoriosfarmacia/:laboratorio_id', to: 'lab_fars#busquedaLaboratoriosAgregados'
  get '/pro_fars/busquedaProductos/:laboratorio/:producto_id', to: 'pro_fars#showBusqueda'
  get '/pro_fars/pro_farmBusqueda/:laboratorio/:producto_id', to: 'pro_fars#pro_farmBusqueda'
  get '/pagos/busqueda/:nombre', to: 'pagos#busqueda'

  

   put '/laboratorio_activo/:id', to: 'laboratorios#activo_update'
   put '/planpaciente_activo/:id', to: 'plan_pacientes#activo_update'
   put '/presentacion_activo/:id', to: 'presentacions#activo_update'
   put '/sustancia_activo/:id', to: 'sustancia#activo_update'
   put '/producto_activo/:id', to: 'productos#activo_update'
   put '/pagos/:id/:idfarmacia', to: 'pagos#update'

   get '/farmacia_plan_paciente/:id', to: 'plan_pacientes#farmacia_plan_paciente'
   get '/plan_paciente/:id', to: 'productos#Plan_Paciente'

     

   root 'sessions#logout'

   namespace :api do
    namespace :v1 do
      get '/laboratorio_consulta', to: 'consultas#index'
      get '/farmacias_cercanas', to: 'consultas#FarmaciasCercanas'
      get '/infoFarmacia/:id', to: 'consultas#InfoFarmacia'
      get '/searchProducto/:nombre', to: 'consultas#SearchProducto'
      get '/infoProducto/:id', to: 'consultas#InfoProducto'
      get '/infoPlanPaciente/:id', to: 'consultas#InfoPlanPaciente'
      get '/FarmaciasCercanaSearch/:id', to: 'consultas#FarmaciasCercanaSearch'
      get '/FarmaciaProductoSearch/:id', to: 'consultas#infoFarmaciaProducto'
    end
  end

  

  

end

app/models/disponibilidad.rb
class Disponibilidad < ActiveRecord::Base
end

app/models/farmacium.rb
class Farmacium < ActiveRecord::Base
    has_secure_password
    
	  validates :nombre, :latitud, :longitud, :cedulaJur, :direccion,:telefono1,:correo,  presence:  { message: "Campo obligatorio" }
	
    validates :correo, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  	validates :telefono1,  numericality: {  message: "Ingrese un número de telefono válido.",only_integer: true }
    validates :telefono1, length: { is: 8, :message => "Debe tener 8 digitos" }
    validates :telefono2,  numericality: {  message: "Ingrese un número de telefono válido.",only_integer: true }
    validates :telefono2, length: { is: 8, :message => "Debe tener 8 digitos" }
    validates :correo, uniqueness: { message: "Correo ya existe" }
    validates :password, presence: { message: "Campo obligatorio" }, on: :create 
  	
	has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
end

app/models/lab_far.rb
class LabFar < ActiveRecord::Base
  belongs_to :farmacia
  belongs_to :laboratorio
end

app/models/laboratorio.rb
class Laboratorio < ActiveRecord::Base
	validates :nombre,  presence:  { message: "Campo obligatorio" }
end

app/models/pago.rb
class Pago < ActiveRecord::Base
  belongs_to :farmacia
  	validates :numcomprobante,  presence:  { message: "Campo obligatorio" }
    validates :numcomprobante,  numericality: {  message: "Ingrese un número.",only_integer: true }
end

app/models/plan_paciente.rb
class PlanPaciente < ActiveRecord::Base
  validates :nombre,  presence:  { message: "Campo obligatorio" }
  belongs_to :laboratorio
end

app/models/presentacion.rb
class Presentacion < ActiveRecord::Base
	validates :descripcion,  presence:  { message: "Campo obligatorio" }
end

app/models/pro_far.rb
class ProFar < ActiveRecord::Base
  belongs_to :farmacia
  belongs_to :producto
  belongs_to :disponibiliad
end

app/models/producto.rb
class Producto < ActiveRecord::Base
  belongs_to :sustancium
  belongs_to :presentacion
  belongs_to :laboratorio
  belongs_to :plan_paciente
  
  validates :oferta, :compra, :numericality => true, :allow_nil => true
  
  validates :nombre,  presence:  { message: "Campo obligatorio" }
  
  
end

app/models/session.rb
class Session < ActiveRecord::Base
	 
	 has_secure_password
end

app/models/sustancium.rb
class Sustancium < ActiveRecord::Base
	validates :descripcion,  presence:  { message: "Campo obligatorio" }
end

app/models/tipo_plan.rb
class TipoPlan < ActiveRecord::Base
  belongs_to :plan_paciente
  validates :descripcion,  presence:  { message: "Campo obligatorio" }
end

app/controllers/disponibilidads_controller.rb
class DisponibilidadsController < ApplicationController
  before_action :set_disponibilidad, only: [:show, :edit, :update, :destroy]
  before_action :autenticacion
  before_action :verificarUsuario

  # GET /disponibilidads
  # GET /disponibilidads.json
  def index
    @disponibilidads = Disponibilidad.all
  end

  # GET /disponibilidads/1
  # GET /disponibilidads/1.json
  def show
  end

  # GET /disponibilidads/new
  def new
    @disponibilidad = Disponibilidad.new
  end

  # GET /disponibilidads/1/edit
  def edit
  end

  # POST /disponibilidads
  # POST /disponibilidads.json
  def create
    @disponibilidad = Disponibilidad.new(disponibilidad_params)

    respond_to do |format|
      if @disponibilidad.save
         format.html { redirect_to "/disponibilidads/new", notice: 'Disponibilidad creada con éxito.' }
      else
        format.html { render :new }
        format.json { render json: @disponibilidad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /disponibilidads/1
  # PATCH/PUT /disponibilidads/1.json
  def update
    respond_to do |format|
      if @disponibilidad.update(disponibilidad_params)
        format.html { redirect_to "/disponibilidads", notice: 'Disponibilidad actualizada con éxito.' }
      else
        format.html { render :edit }
        format.json { render json: @disponibilidad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /disponibilidads/1
  # DELETE /disponibilidads/1.json
  def destroy
    @disponibilidad.destroy
    respond_to do |format|
      msg = { :status => "ok", :message => "Eliminado!" }
        format.json { render :json => msg }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_disponibilidad
      @disponibilidad = Disponibilidad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def disponibilidad_params
      params.require(:disponibilidad).permit(:nombre)
    end
end

app/helpers/consultas_helper.rb
module ConsultasHelper
end

app/helpers/disponibilidads_helper.rb
module DisponibilidadsHelper
end

app/helpers/farmacia_helper.rb
module FarmaciaHelper
end

app/helpers/lab_fars_helper.rb
module LabFarsHelper
end

app/helpers/nombres_helper.rb
module NombresHelper
end

app/helpers/pagos_helper.rb
module PagosHelper
end

app/helpers/pro_fars_helper.rb
module ProFarsHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/disponibilidads/_form.html.erb
<%= bootstrap_form_for(@disponibilidad) do |f| %>
<div class="col-md-6 col-lg-6 col-md-offset-3 col-lg-offset-3 col-xs-offset-1 col-xs-12 col-sm-10">
  <div class="field">
    
    <%= f.text_field :nombre %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>
</div>

app/views/disponibilidads/_linkprincipal.html.erb
<div class="col-lg-12 col-md-12  col-xs-12 col-sm-12">

     <a href="/disponibilidads" class="btn btn-info">
         <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>Disponibilidades
          </a>
          
 </div>

app/views/disponibilidads/edit.html.erb
<h1 class="text-center"> <span class="label label-default">Actualizar Disponibilidad</span></h1>
<br>

<%= render 'form' %>

app/views/disponibilidads/index.html.erb
<script type="text/javascript">
var msj = "<%= notice %>";
  $(document).ready(function() {
  if(msj!='')
    swal(msj, "", "success")

});
</script>
<h1 class="text-center"> <span class="label label-default">Disponibilidad producto Farmacia</span></h1>
<div class="col-lg-6 col-md-6 col-md-offset-3 col-lg-offset-3 col-xs-12 col-sm-12">
<table class="table table-striped table-condensed"">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @disponibilidads.each do |disponibilidad| %>
      <tr id="<%= disponibilidad.id %>">
        <td width="25%"><%= disponibilidad.nombre %></td>
        <td width="10%">
         <a href="/disponibilidads/<%= disponibilidad.id %>/edit" class="btn btn-success">
            <span class="glyphicon glyphicon-edit" aria-hidden="true"></span> Editar
          </a>
           <button class="btn btn-danger" onclick="delete_disponibilidad(<%= disponibilidad.id %>)"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Eliminar</button>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>


<div class="col-lg-6 col-md-6 col-md-offset-3 col-lg-offset-3 col-xs-12 col-sm-12">
<%= link_to 'Nueva Disponibilidad', new_disponibilidad_path, :class => "btn btn-success"%>


</div>

app/views/disponibilidads/new.html.erb
<script type="text/javascript">
var msj = "<%= notice %>";
	$(document).ready(function() {
  if(msj!='')
  	swal(msj, "", "success")

});
</script>
<%= render 'linkprincipal' %>

<h1 class="text-center"> <span class="label label-default">Nueva Disponibilidad</span></h1>
<br>

<%= render 'form' %>