config/routes.rb
Rails.application.routes.draw do
  resources :pagos
  resources :pro_fars
  resources :disponibilidads
  resources :lab_fars
  resources :sessions
  resources :productos
  resources :nombres
  resources :presentacions
  resources :sustancia
  resources :tipo_plans
  resources :plan_pacientes
  resources :laboratorios
  resources :farmacia
  
   get 'logout' => 'sessions#logout'
   get 'login' => 'sessions#new'
   get 'change_password' => 'sessions#new_password'
    get 'reset_password' => 'sessions#reset_password'
   post '/reset_password_update', to: 'sessions#reset_password_update'
   post '/change_password_update', to: 'sessions#update_contrasena'
   get 'lab_farmacia' => 'lab_fars#lab_farm'

   get '/pro_farmacia/:id', to: 'pro_fars#pro_farm'
   
   get '/pro_farmacia_edit/:id', to: 'pro_fars#pro_farm_edit'
   put '/pro_farmacia_update/:id', to: 'pro_fars#pro_farm_update'
   put '/farmacia_verificado/:id', to: 'farmacia#update_verificado'
   get '/farmacias_verificadas', to: 'farmacia#farmacias_verificadas'  
  get '/producto/busqueda/:nombre', to: 'productos#busqueda'
  get '/laboratorio/busqueda/:nombre', to: 'laboratorios#busqueda'
  get '/plan_pacientes/busqueda/:nombre', to: 'plan_pacientes#busqueda'
  get '/presentaciones/busqueda/:nombre', to: 'presentacions#busqueda'
  get '/sustancias/busqueda/:nombre', to: 'sustancia#busqueda'
  get '/farmacias_verificadas/busqueda/:nombre', to: 'farmacia#busquedaVerificadas'
  get '/farmacia/busqueda/:nombre', to: 'farmacia#busqueda'
  get '/lab_fars/busqueda/:laboratorio_id', to: 'lab_fars#busqueda'
  get '/lab_fars/busquedalaboratoriosfarmacia/:laboratorio_id', to: 'lab_fars#busquedaLaboratoriosAgregados'
  get '/pro_fars/busquedaProductos/:laboratorio/:producto_id', to: 'pro_fars#showBusqueda'
  get '/pro_fars/pro_farmBusqueda/:laboratorio/:producto_id', to: 'pro_fars#pro_farmBusqueda'
  get '/pagos/busqueda/:nombre', to: 'pagos#busqueda'

  

   put '/laboratorio_activo/:id', to: 'laboratorios#activo_update'
   put '/planpaciente_activo/:id', to: 'plan_pacientes#activo_update'
   put '/presentacion_activo/:id', to: 'presentacions#activo_update'
   put '/sustancia_activo/:id', to: 'sustancia#activo_update'
   put '/producto_activo/:id', to: 'productos#activo_update'
   put '/pagos/:id/:idfarmacia', to: 'pagos#update'

   get '/farmacia_plan_paciente/:id', to: 'plan_pacientes#farmacia_plan_paciente'
   get '/plan_paciente/:id', to: 'productos#Plan_Paciente'

     

   root 'sessions#logout'

   namespace :api do
    namespace :v1 do
      get '/laboratorio_consulta', to: 'consultas#index'
      get '/farmacias_cercanas', to: 'consultas#FarmaciasCercanas'
      get '/infoFarmacia/:id', to: 'consultas#InfoFarmacia'
      get '/searchProducto/:nombre', to: 'consultas#SearchProducto'
      get '/infoProducto/:id', to: 'consultas#InfoProducto'
      get '/infoPlanPaciente/:id', to: 'consultas#InfoPlanPaciente'
      get '/FarmaciasCercanaSearch/:id', to: 'consultas#FarmaciasCercanaSearch'
      get '/FarmaciaProductoSearch/:id', to: 'consultas#infoFarmaciaProducto'
    end
  end

  

  

end

app/models/producto.rb
class Producto < ActiveRecord::Base
  belongs_to :sustancium
  belongs_to :presentacion
  belongs_to :laboratorio
  belongs_to :plan_paciente
  
  validates :oferta, :compra, :numericality => true, :allow_nil => true
  
  validates :nombre,  presence:  { message: "Campo obligatorio" }
  
  
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: [:show, :edit, :update, :destroy]
     before_action :autenticacion
     before_action :verificarUsuario

  # GET /productos
  # GET /productos.json
  def index
     sql = "select * from productos order by nombre"
    @productos =  Producto.paginate_by_sql(sql, :page => params[:page], :per_page => 7)
  end
  def busqueda
    nombre = params[:nombre]
      
   sql = "select * from productos where LOWER(nombre) like LOWER('%#{nombre}%') order by nombre"
    @productos =  Producto.paginate_by_sql(sql, :page => params[:page], :per_page => 7)
    render :template => "productos/index"
  end

  # GET /productos/1
  # GET /productos/1.json
  def show
  end

  # GET /productos/new
  def new
    @producto = Producto.new
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(producto_params)

    respond_to do |format|
      if @producto.save
           format.html { redirect_to "/productos/new", notice: 'Producto creado con éxito.' }
      else
        format.html { render :new }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # Encontrar el plan paciente con un laboratorio
   def Plan_Paciente
    id = params[:id]
      plan_paciente = PlanPaciente.find_by_sql("SELECT nombre FROM plan_pacientes where laboratorio_id= #{id}")
      render json: plan_paciente
    end

  # PATCH/PUT /productos/1
  # PATCH/PUT /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to "/productos", notice: 'Producto actualizado con éxito.' }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end
   # Metodo para actualizar activo de producto
  def activo_update
      respond_to do |format|
       activo = params[:producto][:activo]
        id = params[:id]
        Producto.where(id: id).update_all(activo: activo )
       msg = { :status => "ok", :message => "Actualizado!" }
        format.json { render :json => msg }
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto.destroy
    respond_to do |format|
       msg = { :status => "ok", :message => "Eliminado!" }
        format.json { render :json => msg }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producto_params
      params.require(:producto).permit(:nombre, :sustancium_id, :presentacion_id, :compra, :oferta, :laboratorio_id, :plan_paciente_id)
    end
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/productos/_form.html.erb
<%= bootstrap_form_for(@producto) do |f| %>
 
<div class="col-md-6 col-lg-6 col-md-offset-3 col-lg-offset-3  col-xs-12 col-sm-12">
  <div class="field">
    <%= f.text_field :nombre %>
  </divdfon>
  <div class="field">
    <%= f.collection_select :sustancium_id, Sustancium.find_by_sql("Select id, descripcion from sustancia order by descripcion"), :id, :descripcion, label: "Sustancia" %>
  </div>
  <div class="field">
    <%= f.collection_select :presentacion_id, Presentacion.find_by_sql("Select id, descripcion from presentacions order by descripcion"), :id, :descripcion, label: "Presentación" %>
  </div> 
  <div class="field">    
    <%= f.collection_select :laboratorio_id, Laboratorio.find_by_sql("Select id, nombre from laboratorios order by nombre"), :id, :nombre %>
  </div>
  <div class="field">    
      <input type="checkbox" id="plan" onclick="Hablilitar();" >Tiene Plan Paciente<br>
  </div>
  </div>
  <br>
  
  <div class="col-md-5 col-lg-5  col-xs-5 col-sm-5">
  <div class="field" id="plan_paciente" style="display:none">    
    <%= f.collection_select :plan_paciente_id, PlanPaciente.find_by_sql("Select id, nombre from plan_pacientes order by nombre"), :id, :nombre, include_blank: true , label: "Plan Paciente"%>
  </div>
  </div>
    <div class="col-md-2 col-lg-2  col-xs-2 col-sm-2 ">
   <div class="field" id="divoferta1" style="display:none" >
    <%= f.number_field :compra, label: "Compra"%>
  </div>
  </div>

  <div class="col-md-2 col-lg-2  col-xs-2 col-sm-2">
    <div class="field" id="divoferta2" style="display:none">
    <%= f.number_field :oferta  ,label: "Regalía"%>
  </div>
  
  </div>



  <div class="col-md-9 col-lg-9 col-xs-12 col-sm-12  col-md-offset-3 col-lg-offset-3">
  <div class="actions">
 <%= f.submit class: 'btn btn-success ' %>
  </div>
  </div>
<% end %>
</div>

app/views/productos/_linkprincipal.html.erb
<div class="col-lg-12 col-md-12  col-xs-12 col-sm-12">

     <a href="/productos" class="btn btn-info">
         <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>Productos
          </a>
          
 </div>

app/views/productos/edit.html.erb
<%= render 'linkprincipal' %>

<h1 class="text-center"> <span class="label label-default">Actualizar Producto</span></h1>
<br>

<%= bootstrap_form_for(@producto) do |f| %>
 
<div class="col-md-6 col-lg-6 col-md-offset-3 col-lg-offset-3  col-xs-12 col-sm-12">
  <div class="field">
    <%= f.text_field :nombre %>
  </divdfon>
  <div class="field">
    <%= f.collection_select :sustancium_id, Sustancium.all, :id, :descripcion, label: "Sustancia" %>
  </div>
  <div class="field">
    <%= f.collection_select :presentacion_id, Presentacion.all, :id, :descripcion, label: "Presentación" %>
  </div> 
  <div class="field">    
    <%= f.collection_select :laboratorio_id, Laboratorio.all, :id, :nombre %>
  </div>
  <div class="field">    
      <input type="checkbox" id="plan" onclick="Hablilitar();" >Tiene Plan Paciente<br>
  </div>
  </div>
  <br>
  <% if @producto.plan_paciente_id != nil %> 
  <div class="col-md-5 col-lg-5  col-xs-5 col-sm-5">
  <div class="field" id="plan_paciente">    
    <%= f.collection_select :plan_paciente_id, PlanPaciente.all, :id, :nombre, include_blank: true , label: "Plan Paciente"%>
  </div>
  </div>
    <div class="col-md-2 col-lg-2  col-xs-2 col-sm-2 ">
   <div class="field" id="divoferta1" >
    <%= f.number_field :compra, label: "Compra"%>
  </div>
  </div>

  <div class="col-md-2 col-lg-2  col-xs-2 col-sm-2">
    <div class="field" id="divoferta2">
    <%= f.number_field :oferta  ,label: "Regalía"%>
  </div>
  </div>
  </div>

	<% else %> 
    <div class="col-md-5 col-lg-5  col-xs-5 col-sm-5">
  <div class="field" id="plan_paciente" style="display:none">    
    <%= f.collection_select :plan_paciente_id, PlanPaciente.all, :id, :nombre, include_blank: true , label: "Plan Paciente"%>
  </div>
  </div>
    <div class="col-md-2 col-lg-2  col-xs-2 col-sm-2 ">
   <div class="field" id="divoferta1" style="display:none" >
    <%= f.number_field :compra, label: "Compra"%>
  </div>
  </div>

  <div class="col-md-2 col-lg-2  col-xs-2 col-sm-2">
    <div class="field" id="divoferta2" style="display:none">
    <%= f.number_field :oferta  ,label: "Regalía"%>
  </div>
  </div>


<% end %>
  <div class="col-md-9 col-lg-9 col-xs-12 col-sm-12  col-md-offset-3 col-lg-offset-3">
  <div class="actions">
 <%= f.submit class: 'btn btn-success ' %>
  </div>
  
<% end %>
</div>

app/views/productos/index.html.erb
<script type="text/javascript">
var msj = "<%= notice %>";
  
   
  if(msj!='')
    swal(msj, "", "success")


</script>

<h1 class="text-center"> <span class="label label-default">Lista de Productos</span></h1>
<br>

  <div class="col-lg-3 col-md-3 col-xs-4 col-sm-4">
   <input type="text" class="form-control"  placeholder="Nombre" name="nombre" id="nombre">
  </div>
 <div class="col-lg-2 col-md-2 col-xs-3 col-sm-3">
  <button type="submit" class="btn btn-success" onclick="busquedaProductos();"><span class="glyphicon glyphicon-search" aria-hidden="true"></span> Buscar</button>
  </div>
<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Sustancia</th>
      <th>Presentación</th>     
      <th>Laboratorio</th>
      <th>Plan paciente</th>
       <th>Oferta</th>
       <th>Activo</th>
      <th>Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @productos.each do |producto| %>
      <tr id="<%= producto.id %>">
        <td width="10%"><%= producto.nombre %></td>
        <td width="10%"><%= producto.sustancium.descripcion %></td>
        <td width="10%"><%= producto.presentacion.descripcion %></td>       
        <td width="10%"><%= producto.laboratorio.nombre %></td>
        <% if producto.plan_paciente != nil %> 
           <td width="10%"><%= producto.plan_paciente.nombre %></td>
           <td width="10%"><%= producto.compra %>+<%= producto.oferta %></td>
         <% else  %> 
           <td width="10%"></td>
           <td width="10%"></td>
        <% end %>
        
        
          <td width="15%"> <% if producto.activo == true %> 

            <label><input type="checkbox" value="" onclick="Activo(<%= producto.id %>, <%= producto.activo %>, 'producto');" checked>Activo</label>
         <% else %> 

             <label><input type="checkbox" value="" onclick="Activo(<%= producto.id %>, <%= producto.activo %>,'producto');">Activo</label>
        <% end %></td>
        <td width="20%">
          <a href="/productos/<%= producto.id %>" class="btn btn-info">
         <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span> 
          </a>
          <a href="/productos/<%= producto.id %>/edit" class="btn btn-success">
            <span class="glyphicon glyphicon-edit" aria-hidden="true"></span> 
          </a>
           <button class="btn btn-danger" onclick="delete_producto_id(<%= producto.id %>)"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span> </button>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="col-md-12 col-lg-12 col-xs-12 col-sm-12  ">
<%= link_to 'Nuevo producto', new_producto_path, :class => "btn btn-success"%>
</div>
 <div class="col-lg-8 col-md-8 col-md-offset-4 col-lg-offset-4 col-xs-offset-4 col-sm-offset-4 col-xs-8 col-sm-8 " >
        <%= will_paginate @productos, renderer: BootstrapPagination::Rails %>
    </div>

app/views/productos/new.html.erb
<script type="text/javascript">
var msj = "<%= notice %>";
	$(document).ready(function() {
  if(msj!='')
  	swal(msj, "", "success")

});
</script>
<%= render 'linkprincipal' %>

<h1 class="text-center"> <span class="label label-default">Nuevo Producto</span></h1>
<br>

<%= render 'form' %>

app/views/productos/show.html.erb
<%= render 'linkprincipal' %>
<%= bootstrap_form_for(@producto) do |f| %>
 
<div class="col-md-6 col-lg-6 col-md-offset-3 col-lg-offset-3  col-xs-12 col-sm-12">
  <div class="form-group">
    <%= f.text_field :nombre ,:readonly => true%>
  </div>

  <div class="form-group">
  <label class="control-label required" for="producto_nombre">Sustancia</label>
    <input readonly="readonly" class="form-control" type="text" value=" <%= @producto.sustancium.descripcion%>">
  </div> 
   <div class="form-group">
   <label class="control-label required" for="producto_nombre">Presentación</label>
    <input readonly="readonly" class="form-control" type="text" value=" <%= @producto.presentacion.descripcion%>">
  </div> 
  <div class="form-group">
  <label class="control-label required" for="producto_nombre">Laboratorio</label>
    <input readonly="readonly" class="form-control" type="text" value=" <%= @producto.laboratorio.nombre%>">
  </div> 
  </div>
  <% end %>
<% if (@producto.plan_paciente_id != nil) %>

 
 <!-- <div class="col-md-6 col-lg-6 col-md-offset-3 col-lg-offset-3  col-xs-12 col-sm-12"> -->
  <div class="col-md-3 col-lg-3 col-md-offset-3 col-lg-offset-3  col-xs-12 col-sm-12">
  <div class="field" >
  <label class="control-label required" for="producto_nombre">Plan Paciente</label>    
    <input readonly="readonly" class="form-control" type="text" value=" <%= @producto.plan_paciente.nombre%>">
  </div>
  </div>

    <div class="col-md-1 col-lg-1  col-xs-6 col-sm-6 col-md-offset-1 col-lg-offset-1">
   <div class="field" >
   <label class="control-label required" for="producto_nombre">Compra</label>
    <input readonly="readonly" class="form-control" type="text" value=" <%= @producto.compra %>">
  </div>
  </div>

  <div class="col-md-1 col-lg-1  col-xs-6 col-sm-6">
    <div class="field" >
    <label class="control-label required" for="producto_nombre">Oferta</label>
    <input readonly="readonly" class="form-control" type="text" value=" <%= @producto.oferta%>">
  </div>
  </div>
<% end %>

<div class="col-lg-6 col-md-8 col-md-offset-5 col-lg-offset-5 col-xs-12 col-sm-12">
<br>
          <a href="/productos/<%= @producto.id %>/edit" class="btn btn-success">
            <span class="glyphicon glyphicon-edit" aria-hidden="true"></span> Editar
          </a>
 </div>